reverting version bump for k8s model dependency, because it's causing CNFE
when creating cluster:

Exception in thread "OkHttp Dispatcher" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/api/model/extensions/DaemonSet
	at io.fabric8.kubernetes.client.handlers.DaemonSetHandler.getKind(DaemonSetHandler.java:38)
	at io.fabric8.kubernetes.client.Handlers.register(Handlers.java:43)
	at io.fabric8.kubernetes.client.Handlers.discoverHandlers(Handlers.java:66)
	at io.fabric8.kubernetes.client.Handlers.<clinit>(Handlers.java:39)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.handlerOf(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:364)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.acceptVisitors(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:285)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:203)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:65)
	at io.radanalytics.operator.cluster.ClusterOperator.onAdd(ClusterOperator.java:30)
	at io.radanalytics.operator.cluster.ClusterOperator.onAdd(ClusterOperator.java:15)
	at io.radanalytics.operator.common.AbstractOperator$1.eventReceived(AbstractOperator.java:108)
	at io.radanalytics.operator.common.AbstractOperator$1.eventReceived(AbstractOperator.java:95)
	at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:237)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.api.model.extensions.DaemonSet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)